### PR TITLE
Feature/product flavors

### PR DESCRIPTION
**Pull request by ted3x**

### CODE REVIEW

**Review by Edna001 — APPROVED** [review]

**Comment by anarusadzeSpace** [comment]
maybe you should change your base to development instead of  feature/handle_network/ARC-708

**Comment by ted3x** [comment]
> maybe you should change your base to development instead of feature/handle_network/ARC-708

Changed

**Comment by ted3x** [comment]
> maybe you should change your base to development instead of feature/handle_network/ARC-708

Changed

**Comment by ted3x** [comment]
> maybe you should change your base to development instead of feature/handle_network/ARC-708

Changed

**Pull request merged**
